### PR TITLE
Add support for Generic Template Resolvers

### PR DESCRIPTION
**Pull request by BierDav**
Also added NullableChainedTranslators

This should resolve: #550

### CODE REVIEW

**Comment by BierDav** [comment]
Btw. this would be an possible implementation for a template resolver that makes use of this generics:
```

type CtI18nTemplateArgs = string | number | boolean | ((children?: JSX.Element) => JSX.Element);
  function resolveJSXTemplate(string: string, wrappers: {
        [key: string]: ((children?: JSX.Element) => JSX.Element)
    }, regex: RegExp): JSX.Element {
        const matches = Array.from(string.matchAll(regex))
        const resultArray = []
        let index = 0
        for (let match of matches) {
            resultArray.push(string.slice(index, match.index))
            index = match.index! + match[0].length
            const wrapper = wrappers[match[1]]
            resultArray.push(wrapper(match[3] ? resolveJSXTemplate(match[3], wrappers, regex) : undefined))
        }
        resultArray.push(string.slice(index))
        return resultArray
    }

    function resolveTemplate(string: string, args?: BaseTemplateArgs<CtI18nTemplateArgs>) {
        if (!args)
            return string;
        const wrappers: { [key: string]: ((children: JSX.Element) => JSX.Element) } = {}
        for (let prop in args)
            if (typeof args[prop] === 'function') {
                wrappers[prop] = args[prop] as ((children: JSX.Element) => JSX.Element)
                delete args[prop];
            }
        const result = i18n.resolveTemplate(string, args as BaseTemplateArgs)
        if (Object.keys(wrappers).length == 0)
            return result
        const regexExp = new RegExp(`{{\\s*(${Object.keys(wrappers).join("|")})\\s*}}((.*?){{\\s*(\\1)_end\\s*}})?`, "g")
        return resolveJSXTemplate(result, wrappers, regexExp)
    }

    const translator = i18n.translator(dict, resolveTemplate);
```

```
{
"hello_world": "Hello {{link_wrapper}}Link{{link_wrapper_end}}"
}
```

**Comment by BierDav** [comment]
Can someone review this, the test is not failing due to an error of mine

**Comment by thetarnav** [comment]
I should not be allowed near git lol, I'll try to fix this

**Comment by BierDav** [comment]
I think I cannot reopen the merge request either, btw. hmm i haven't thought about that usecase yet, but fell free to make string a default, if it makes sense

**Comment by BierDav** [comment]
ahh i know why you cannot reopen, because of an force push on the main branch, but if you have the changes in a separate branch it doesn't matter anyways

**Pull request closed without merging**
