### PR TITLE
[pagination] Prevent wrong pages slice

### PR DESCRIPTION
**Pull request by martinpengellyphillips**
When `maxPages` is greater than `pages`, ensure the min value of the computed start for slicing is 0 (rather than a negative number). A negative number starts indexing from the end of the array causing an incorrect slice to be made. 

E.g. `10 pages - 13 maxPages = pages[-3, 13] = pages[8,9,10]`

### CODE REVIEW

**Comment by atk** [comment]
maxPages should in its usage not ever be more than pages. It would be better to derive it:

```ts
const maxPages = () => Math.min(opts().maxPages, opts().pages);
```

And use that throughout the calculations (including the slice of pages. So the start calculation would not get any more convoluted (I was pretty close to add a comment or extract variables to explain the meaning of both parts).

**Comment by martinpengellyphillips** [comment]
Makes sense, I'll do that.

**Comment by martinpengellyphillips** [comment]
@atk ready for another look.

**Comment by atk** [comment]
As an aside, thanks for testing this more thoroughly. 👍

**Comment by atk** [comment]
Closed with PR#314.

**Pull request closed without merging**
